### ISSUE TITLE
Any plan to merge PutTextUnicode into shimat's upstream repo?

### ISSUE THREAD

**Issue by sdcb** [AvenSun/OpenCvSharpSlim#4]
Seems hard, because it's already too complexed.

**Comment by AvenSun** [comment]
Hi @sdcb 

currently the native implementation of **PutTextUnicode** in **OpenCvSharpSlim** is written by me.
frankly speaking, It's been several years since I finished it. but it only works on windows platform. 
on the contrary, **OpenCv** can work on many platforms.
that's why I didn't make this feature into @shimat's upstream repo.
what's your opinion on this?

**Comment by sdcb** [comment]
just curious, Windows only, so is it Direct2D or FreeType?

**Comment by AvenSun** [comment]
yep, It's something like that.
It's implemented via cpp and wrapped for c#.
of course, freetype can do this job well for all platforms.
but it's a little more complex and not lightweight for **slim feature**.
actually I‘ve already finished implementations for all platforms long time ago.
but It belongs to my company.  I can't release source code now. 
It's against the company's regulations,
